"""Initial typed business tables and synchronization audit (immutable migration)."""
from alembic import op
import sqlalchemy as sa
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """场景 1.2：建立业务表和序列化写入锁。"""
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_tombstones',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('product', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('pieces', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('days_late', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('imported_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_customer'), 'orders', ['customer'], unique=False)
    op.create_index(op.f('ix_orders_due_date'), 'orders', ['due_date'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('production_log',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('pieces_completed', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('imported_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'stage', name='uq_production_date_stage')
    )
    op.create_index(op.f('ix_production_log_date'), 'production_log', ['date'], unique=False)
    op.create_table('sync_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_source'), 'sync_logs', ['source'], unique=False)
    op.create_table('workshops',
    sa.Column('workshop_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capacity_pieces_per_day', sa.Integer(), nullable=False),
    sa.Column('pickup_lead_days', sa.Integer(), nullable=False),
    sa.Column('defect_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('cost_per_piece', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('makes', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('max_batch_pieces', sa.Integer(), nullable=True),
    sa.Column('current_queue_days', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('imported_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop_id')
    )
    # ### end Alembic commands ###
    op.execute(sa.text('INSERT INTO sync_lock (id) VALUES (1)'))


def downgrade() -> None:
    """场景 1.2：仅在人工决定回退时删除表。"""
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshops')
    op.drop_index(op.f('ix_sync_logs_source'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_table('sync_lock')
    op.drop_index(op.f('ix_production_log_date'), table_name='production_log')
    op.drop_table('production_log')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_due_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('data_tombstones')
    # ### end Alembic commands ###
