"""Evaluate the locked requirements for Linux Python 3.11 even on Windows."""
from pathlib import Path
from packaging.markers import default_environment
from packaging.requirements import Requirement

root = Path(__file__).resolve().parents[2]
environment = default_environment()
environment.update(python_version='3.11', python_full_version='3.11.15',
    sys_platform='linux', platform_system='Linux', os_name='posix',
    platform_machine='x86_64', platform_python_implementation='CPython')
requirements = []
for line in (root / 'requirements.txt').read_text().splitlines():
    if not line.strip() or line.lstrip().startswith('#'):
        continue
    requirement = Requirement(line)
    if not requirement.marker or requirement.marker.evaluate(environment):
        requirement.marker = None
        requirements.append(str(requirement))
(Path(__file__).parent / 'requirements-linux311.txt').write_text(
    '# Generated by export_requirements.py from requirements.txt\n' + '\n'.join(requirements) + '\n')
