/* Shared workflow chat UI. Transport is implemented in ai-stream.js. */
const API_BASE = ['8765',''].includes(location.port) ? 'http://127.0.0.1:8000' : location.origin;
let aiBusy=false, aiGeneration=0, aiController=null, apiLabel='Checking AI backend…';
try { const history=JSON.parse(sessionStorage.getItem('threadpilot-llm-chat')||'{}');state.chat=history.chat||[];state.chatIds=history.ids||[]; } catch {state.chat=[];state.chatIds=[];}
function persistAI(){try{sessionStorage.setItem('threadpilot-llm-chat',JSON.stringify({chat:state.chat,ids:state.chatIds}))}catch{}save()}
// Hide the backend's duplicate citation line in display only; keep raw answers for export.
function displayAnswer(text){return String(text??'').replace(/\r?\n\r?\nSource evidence:[^\r\n]*(?:\r?\n|$)/g,'\n\n')}
const sourceAiPage=aiPage, sourceShell=shell;
shell=function(content){return sourceShell(content).replace('AI and delivery are local simulations','AI via FastAPI / OpenAI · delivery remains simulated')};
aiPage=function(){return sourceAiPage().replace('Answers are calculated locally from your CSVs. No language-model service is connected.','Answers use OpenAI intent recognition and current database records.').replace('Conversation context stays with the selected source orders.','Multi-turn analysis · Full responses via FastAPI / OpenAI.')};
composer=function(){return `<form class="composer" data-form="chat"><textarea aria-label="Ask ThreadPilot" name="visible-question" placeholder="Ask about an order, a risk, or your next move…" required maxlength="1500" ${aiBusy?'disabled':''}></textarea><div class="actions"><small>Context · ${esc(state.selected)}<br><span class="api-status">${esc(apiLabel)}</span></small><div class="actions">${btn('voice','♩','','aria-label="Voice input"')}<button class="primary" type="submit" ${aiBusy?'disabled':''}>${aiBusy?'Thinking…':'Send ↗'}</button></div></div></form>`};
chatHTML=function(){return state.chat.map(m=>m.role==='user'?`<div class="bubble user">${esc(m.text)}</div>`:m.role==='error'?`<div class="bubble"><p>${esc(m.question)}</p><p class="error" role="alert">${esc(m.text)}</p>${btn('retry-ai','Retry')}${m.requestId?`<p><small>Request ${esc(m.requestId)}</small></p>`:''}</div>`:`<div class="bubble"><div class="eyebrow">✧ THREADPILOT / OPENAI</div><div class="note">${esc(displayAnswer(m.text))}</div>${m.ids?.length?`<div class="ai-cards">${m.ids.filter(find).map(id=>{const o=find(id);return `<div class="ai-order"><strong>${o.id} · ${esc(o.customer)}</strong><p class="muted">${titleCase(o.stage)} · ${dueLabel(o)}</p>${riskBadge(o)}<div class="actions">${link('order','View order',id,'button small-button')}${link('evidence','Evidence',id,'button small-button')}</div></div>`}).join('')}</div>`:''}${m.order&&find(m.order)?`<div class="actions">${link('evidence','View evidence',m.order)}${find(m.order).status==='In progress'?link('draft','Draft chase-up',m.order)+btn('watch','Create watch','',`data-id="${m.order}"`):link('order','View order',m.order)}</div>`:''}<p class="spaced"><small>Model: ${esc(m.model)} · Sources used: ${esc(m.source||'No source cited')}</small></p></div>`).join('')+(aiBusy?'<div class="bubble" role="status">Thinking with your source records…</div>':'')};
function redrawAI(){if(drawerOpen)openAIDrawer();else if(route==='ai')render();$$('[data-form="chat"] textarea').forEach(x=>x.disabled=aiBusy);$$('[data-form="chat"] button[type="submit"]').forEach(x=>x.disabled=aiBusy)}
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='new-chat'||action==='confirm-reset'){aiGeneration++;aiController?.abort();aiBusy=false;queueMicrotask(persistAI)}if(action==='retry-ai'){const last=state.chat.findLast(m=>m.role==='error');if(last)ask(last.question)}},true);
fetch(API_BASE+'/api/v1/health').then(r=>r.json()).then(h=>{apiLabel=h.configured?`OpenAI · ${h.model} · Ready`:'API key not configured · Set backend/.env';$$('.api-status').forEach(x=>x.textContent=apiLabel)}).catch(()=>{apiLabel='Backend offline · Start FastAPI on port 8000';$$('.api-status').forEach(x=>x.textContent=apiLabel)});
render();
