/* Validated workflow SSE display. Final metadata unlocks evidence and action cards. */
let aiLiveText='', aiUserStopped=false;
let workflowSession=sessionStorage.getItem('threadpilot-workflow-session'), workflowConfirmation=null;
document.addEventListener('click',e=>{if(['new-chat','confirm-reset'].includes(e.target.closest('[data-action]')?.dataset.action)){workflowSession=null;workflowConfirmation=null;sessionStorage.removeItem('threadpilot-workflow-session')}},true);
const beforeStreamChat=chatHTML, beforeStreamComposer=composer;
composer=function(){return beforeStreamComposer().replace('Thinking…','Generating…')+(aiBusy?`<div class="actions spaced">${btn('stop-ai','Stop generating')}</div>`:'')};
chatHTML=function(){const last=state.chat.findLast(m=>m.role==='assistant');const links=(last?.evidence||[]).filter(e=>/^\/api\/v1\/evidence\/(orders|production_log|workshops)\.csv\/\d+$/.test(e.url));return beforeStreamChat().replace('<div class="bubble" role="status">Thinking with your source records…</div>',`<div class="bubble"><div class="eyebrow">✧ THREADPILOT / GENERATING</div><div class="note" data-live-answer>${esc(aiLiveText||'Connecting to model…')}</div><small>Validating intent and source records…</small></div>`)+(links.length?`<details class="bubble"><summary>Latest answer · ${links.length} original source rows · ${esc(last.businessDate)}</summary><div class="actions">${links.map(e=>`<a href="${API_BASE+e.url}" target="_blank" rel="noopener">${esc(e.source)} row ${e.row}</a>`).join(' · ')}</div></details>`:'')};
function paintLive(){document.querySelectorAll('[data-live-answer]').forEach(el=>{const panel=el.closest('.drawer');const follow=panel?panel.scrollHeight-panel.scrollTop-panel.clientHeight<120:document.documentElement.scrollHeight-scrollY-innerHeight<120;el.textContent=aiLiveText||'Connecting to model…';if(follow){if(panel)panel.scrollTop=panel.scrollHeight;else window.scrollTo(0,document.documentElement.scrollHeight)}})}
ask=async function(question){const q=question.trim();if(!q||aiBusy)return;if(q.length>1500){toast('Keep your question under 1500 characters.');return}
 state.chat=state.chat.filter(m=>m.role!=='error');const generation=aiGeneration;
 aiBusy=true;aiLiveText='';aiUserStopped=false;aiController=new AbortController();const controller=aiController;let timer,reader,complete=false;const resetTimeout=()=>{clearTimeout(timer);timer=setTimeout(()=>controller.abort(),90000)};resetTimeout();state.chat.push({role:'user',text:q});persistAI();if(!drawerOpen&&route!=='ai')go('ai');redrawAI();requestAnimationFrame(()=>document.querySelector('[data-live-answer]')?.scrollIntoView({block:'end'}));
 try{const response=await fetch(API_BASE+'/api/v1/workflow/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({message:q,session_id:workflowSession,confirmation_id:workflowConfirmation,selected_order_id:workflowSession?null:state.selected})});
 if(!response.ok){const data=await response.json();throw Object.assign(new Error(data.error?.message||'Request rejected. Check the backend or start a new conversation.'),{requestId:data.error?.request_id})}
 if(!response.headers.get('content-type')?.includes('text/event-stream')||!response.body)throw new Error('The backend is not serving a stream. Restart the updated backend.');
 reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';
 function processFrame(frame){const lines=frame.split('\n');const type=lines.find(l=>l.startsWith('event:'))?.slice(6).trim();const raw=lines.filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trimStart()).join('\n');if(!raw)return;const data=JSON.parse(raw);
 if(type==='delta'){aiLiveText+=data.text;paintLive()}
 if(type==='error')throw Object.assign(new Error(data.message||'Generation failed.'),{requestId:data.request_id});
 if(type==='done'){if(typeof data.answer!=='string'||!data.answer.trim())throw new Error('The completed answer was empty.');workflowSession=data.state?.session_id||workflowSession;workflowConfirmation=data.confirmation_id||null;if(workflowSession)sessionStorage.setItem('threadpilot-workflow-session',workflowSession);const ids=(data.order_ids||[]).filter(find);state.chat.push({role:'assistant',text:data.answer,ids,order:data.selected_order_id,source:(data.sources||[]).join(', '),model:data.model,requestId:data.request_id,evidence:data.evidence||[],businessDate:data.business_date});state.chatIds=ids;if(data.selected_order_id&&find(data.selected_order_id))state.selected=data.selected_order_id;complete=true}}
 while(!complete){const part=await reader.read();if(generation!==aiGeneration)return;resetTimeout();buffer+=decoder.decode(part.value||new Uint8Array(),{stream:!part.done});buffer=buffer.replace(/\r\n/g,'\n');let index;while((index=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,index);buffer=buffer.slice(index+2);processFrame(frame);if(complete)break}if(part.done){if(!complete)throw new Error('The connection ended before the answer was complete. Please retry.');break}}
 }catch(error){if(generation!==aiGeneration)return;state.chat.pop();const reason=error.name==='AbortError'?(aiUserStopped?'Generation stopped.':'No response received for 90 seconds. Please retry.'):error instanceof TypeError?'Connection interrupted. Check FastAPI and try again.':error.message;state.chat.push({role:'error',question:q,text:reason+(aiLiveText?'\n\nIncomplete preview (not saved as an answer):\n'+aiLiveText:''),requestId:error.requestId});
 }finally{clearTimeout(timer);try{await reader?.cancel()}catch{}if(generation===aiGeneration){aiBusy=false;aiController=null;aiLiveText='';persistAI();redrawAI()}}
};
document.addEventListener('click',e=>{if(e.target.closest('[data-action]')?.dataset.action==='stop-ai'){aiUserStopped=true;aiController?.abort()}},true);
const seenWorkflowNotifications=new Set();
setInterval(async()=>{if(!workflowSession||document.hidden)return;try{const session=workflowSession;const response=await fetch(API_BASE+'/api/v1/workflow/notifications/'+session);if(!response.ok||session!==workflowSession)return;for(const item of await response.json()){if(!seenWorkflowNotifications.has(item.id)){seenWorkflowNotifications.add(item.id);toast(item.order_id+': '+item.message)}}}catch{}},30000);
render();
