'use strict';
const SNAPSHOT=TRACK1_DATA.today+' · database business date';
const TODAY=TRACK1_DATA.today;
const dayDiff=(a,b)=>Math.round((Date.parse(a+'T12:00:00Z')-Date.parse(b+'T12:00:00Z'))/86400000);
const stages=['KNITTING','ASSEMBLY','WASHING','PACKING'];
const activeRaw=TRACK1_DATA.orders.filter(o=>o.status==='IN_PROGRESS');
const orders=TRACK1_DATA.orders.map((r,index)=>{
 const active=r.status==='IN_PROGRESS',idle=active?Math.max(0,dayDiff(TODAY,r.last_activity_date)):0,daysToDue=dayDiff(r.due_date,TODAY);
 const share=activeRaw.filter(x=>x.customer===r.customer).length/activeRaw.length;
 const factors=active?[Math.min(35,idle*5),daysToDue<0?35:daysToDue<=3?28:daysToDue<=7?20:daysToDue<=14?10:0,(4-stages.indexOf(r.current_stage))*5,Math.round(share*10)]:[0,0,0,0];
 return {id:r.order_id,customer:r.customer,product:r.product,category:r.category,qty:Number(r.pieces),stage:r.current_stage,due:r.due_date,last:r.last_activity_date,idle,score:factors.reduce((a,b)=>a+b,0),factors,status:active?'In progress':'Complete',completed:r.completed_date,daysLate:r.days_late===''?null:Number(r.days_late),daysToDue,sourceRow:r._record_id||index+2,raw:r};
});
const defaults={notes:[],watches:[],messages:[],audit:[],assessments:[],settings:{time:'07:00',idle:'3',voice:false,briefing:true},chat:[],chatIds:[],selected:'ORD-002'};
let state;try{state={...JSON.parse(JSON.stringify(defaults)),...JSON.parse(localStorage.getItem('threadpilot-track1-v2')||'{}')}}catch{state=JSON.parse(JSON.stringify(defaults))}
let route,params,drawerOpen=false,exception='production',riskId='ORD-002',messageTab='watches',feasibility=state.request||{category:'TOPS',qty:800,due:'2026-04-25',outside:true},pending=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const find=id=>orders.find(o=>o.id===id);
const current=()=>find(params.get('id'))||find(state.selected)||orders[0];
const date=d=>new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric',timeZone:'UTC'});
const level=o=>o.score>=80?'Severe':o.score>=60?'Warning':'Watch';
const badge=o=>`<span class="badge ${level(o).toLowerCase()}">${level(o)} · ${o.score}</span>`;
const link=(r,label,id='',cls='button')=>`<a class="${cls}" href="#/${r}${id?'?id='+encodeURIComponent(id):''}">${label}</a>`;
const btn=(action,label,cls='',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const idAttr=o=>`data-id="${o.id}"`;
function save(){try{localStorage.setItem('threadpilot-track1-v2',JSON.stringify(state))}catch{toast('Browser storage is unavailable. Changes last only for this session.')}}
function audit(type,description,details={}){const a={id:'ACT-'+String(state.audit.length+1).padStart(3,'0'),time:new Date().toISOString(),type,description,details:JSON.parse(JSON.stringify(details))};state.audit.unshift(a);save();return a}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4200)}
function go(path){location.hash='/'+path}
function head(title,sub,actions=''){return `<div class="page-head"><div><div class="eyebrow">THREADPILOT / MANAGEMENT WORKSPACE</div><h1>${title}</h1><p class="muted">${sub}</p></div><div class="actions">${actions}</div></div>`}
function orderActions(o){return `${link('evidence','View evidence',o.id)}${btn('ask-order','Ask AI','',idAttr(o))}${link('draft','Draft chase-up',o.id,'button primary')}`}
const nav=[['dashboard','◫','Dashboard'],['orders','▤','Orders'],['exceptions','△','Exceptions'],['risk','↗','Risk Orders'],['feasibility','▦','Feasibility'],['ai','✧','AI Co-Pilot'],['messages','▧','Messages & Watches'],['activity','◷','Activity Log'],['settings','⚙','Settings']];
function shell(content){const active={order:'orders',evidence:'orders',draft:'messages',result:'feasibility'}[route]||route;return `<aside class="sidebar"><a href="#/cover" class="brand"><span class="brandmark">↝</span>ThreadPilot</a><nav>${nav.map(([r,i,t])=>`<a href="#/${r}" class="${active===r?'active':''}" ${active===r?'aria-current="page"':''}><span class="nav-icon">${i}</span>${t}</a>`).join('')}</nav><footer><strong>Track 1 Apparel</strong><br><span class="muted">General Manager workspace</span><br><span class="badge spaced">LOCAL DEMO</span></footer></aside><main class="app-main"><header class="topbar">${btn('menu','☰','mobile-menu','aria-label="Toggle navigation"')}<form class="search-form" id="global-search"><span>⌕</span><label class="screenreader" for="global-query">Search orders or customers</label><input id="global-query" name="query" class="search" placeholder="Search orders or customers…" required></form><div class="toolbar"><small class="freshness">Data · ${SNAPSHOT}</small>${btn('ai-drawer','✧ Ask AI','primary')}<a class="button" href="#/messages" aria-label="Open messages">♧</a><span class="language badge">EN</span><span class="avatar">JW</span></div></header><div class="demo-banner">Interactive local demo · 120 source orders · Business date Apr 01, 2026 · AI and delivery are local simulations</div><div class="page">${content}</div></main>${btn('ai-drawer','✧ Ask AI','primary floating')}`}
function cover(){return `<main class="cover"><section class="cover-left"><a class="brand" href="#/cover"><span class="brandmark">↝</span>ThreadPilot</a><div class="eyebrow">GENERAL MANAGER’S AI CO-PILOT</div><h1>See clearly.<br>Decide <em>confidently.</em></h1><p>Your factory’s morning, brought into focus. Understand what matters. Follow the evidence. Take the next step.</p><div class="actions">${link('dashboard','Enter today’s dashboard ↗','','button primary')}${btn('voice','♩','', 'aria-label="Voice input"')}</div><div class="grid three spaced"><div><strong>01</strong><br><small>Spot the risk</small></div><div><strong>02</strong><br><small>See the evidence</small></div><div><strong>03</strong><br><small>Act with confidence</small></div></div><footer><strong>Track 1 Apparel</strong><br><small>Data updated ${SNAPSHOT}<br>Local demonstration · English interface</small></footer></section><section class="cover-right"><div class="hero-photo"><img src="assets/factory-hero.png" alt="Bright apparel production workshop"><div class="float-label">✧ Your morning brief is ready</div><div class="float-label">✓ Evidence behind every decision</div></div><div class="cover-caption"><h2>A calmer view of a complex day.</h2><p class="muted">From the production floor to your next decision.</p></div></section></main>`}
function composer(){return `<form class="composer" data-form="chat"><textarea aria-label="Ask ThreadPilot" name="visible-question" placeholder="Ask about an order, a risk, or your next move…" required maxlength="1500"></textarea><div class="actions"><small>Context · ${esc(state.selected)} · Demo</small><div class="actions">${btn('voice','♩','','aria-label="Voice input"')}<button class="primary" type="submit">Send ↗</button></div></div></form>`}
function messagesPage(){return head('Messages & standing watches','Keep follow-ups visible, with human review at every external action.',btn('watch','Create watch','primary',idAttr(current())))+`<div class="tabs">${['watches','messages','assessments'].map(t=>btn('message-tab',({watches:'Standing watches',messages:'Demo receipts',assessments:'Saved assessments'})[t],messageTab===t?'active':'',`data-tab="${t}"`)).join('')}</div>${messageTab==='watches'?`<div class="callout">Watches run only when you click “Check now” in this local demo. No background scheduler or notifications are connected.</div><div class="grid equal">${state.watches.map(w=>`<section class="card"><div class="section-heading"><h2>${w.order}</h2><span class="badge ${w.active?'watch':''}">${w.active?'Active':'Paused'}</span></div><p>Alert when inactivity reaches ${w.threshold} calendar days.</p><p class="muted">${esc(w.last||'Not checked yet')}</p><div class="actions">${btn('toggle-watch',w.active?'Pause':'Resume','',`data-id="${w.id}"`)}${btn('check-watch','Check now','',`data-id="${w.id}" ${w.active?'':'disabled'}`)}${link('order','View order',w.order)}</div></section>`).join('')||'<section class="card empty"><h2>No standing watches yet.</h2><p>Create a watch from any order or risk explanation.</p></section>'}</div>`:messageTab==='messages'?`<div class="grid equal">${state.messages.map(m=>`<section class="card"><span class="badge watch">Simulated receipt</span><h2 class="spaced">${m.order}</h2><p>${esc(m.recipient)} · ${m.channel}</p><p class="note">${esc(m.text)}</p><small>${m.id} · ${formatWorkspaceTime(m.time)}</small><div class="actions spaced">${link('activity','View audit record')}</div></section>`).join('')||'<section class="card empty">No confirmed demo messages.</section>'}</div>`:`<div class="grid equal">${state.assessments.map(a=>`<section class="card"><h2>${a.qty} ${a.category}</h2><p>Requested ${date(a.due)} · Estimated ${date(a.estimate)}</p><small>${a.outside?'External scenario allowed':'Internal only'}</small></section>`).join('')||'<section class="card empty">No saved assessments.</section>'}</div>`}`}
function activityPage(){return head('Activity log','A local record of reviewed actions, confirmations and simulated receipts.',btn('export-audit','Export audit JSON'))+`<section class="card"><label class="field">Filter action type<select id="audit-filter"><option value="">All actions</option>${[...new Set(state.audit.map(a=>a.type))].map(t=>`<option>${t}</option>`).join('')}</select></label><div id="audit-results">${auditRows(state.audit)}</div></section>`}
function auditRows(list){return list.map(a=>`<details><summary>${a.id} · ${esc(a.type)} <small> · ${formatWorkspaceTime(a.time)}</small></summary><p>${esc(a.description)}</p><pre>${esc(formatWorkspaceText(JSON.stringify(a.details,null,2)))}</pre></details>`).join('')||'<div class="empty">No recorded actions. Confirm a note, watch, assessment, settings change, or demo message to begin.</div>'}
function render(){const raw=location.hash.slice(1)||'/cover';const [path,query='']=raw.split('?');route=path.replace(/^\//,'');params=new URLSearchParams(query);closeOverlay();const views={cover,dashboard,orders:ordersPage,predictions:()=>window.renderPredictions?window.renderPredictions():'Loading predictions…',order:orderDetail,exceptions:exceptionsPage,risk:riskPage,feasibility:feasibilityPage,result:resultPage,evidence:evidencePage,draft:draftPage,ai:aiPage,messages:messagesPage,activity:activityPage,settings:settingsPage};if(['order','evidence','draft'].includes(route)&&params.has('id')&&!find(params.get('id'))){$('#app').innerHTML=shell(head('Order not found','This order is not included in the demo records.',link('orders','Return to orders')));return}$('#app').innerHTML=route==='cover'?cover():shell(views[route]?views[route]():head('Page not found','Choose a page from the navigation.',link('dashboard','Open dashboard')));document.title=`ThreadPilot · ${route.charAt(0).toUpperCase()+route.slice(1)}`;if(route==='orders')filterOrders();window.scrollTo(0,0)}
function closeOverlay(){$('#overlay').innerHTML='';drawerOpen=false;pending=null;if(closeOverlay.focus?.isConnected)closeOverlay.focus.focus()}
function modal(title,content,action,label='Confirm'){closeOverlay.focus=document.activeElement;$('#overlay').innerHTML=`<div class="overlay modal-wrap"><section class="modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="drawer-header"><h2>${title}</h2>${btn('close','×','','aria-label="Close dialog"')}</div>${content}<div class="actions spaced">${btn(action,label,'primary')}${btn('close','Cancel')}</div></section></div>`;setTimeout(()=>$('#overlay input, #overlay textarea, #overlay button')?.focus(),0)}
function openAIDrawer(){closeOverlay.focus=document.activeElement;drawerOpen=true;$('#overlay').innerHTML=`<div class="overlay"><aside class="drawer" role="dialog" aria-modal="true" aria-label="AI Co-Pilot"><div class="drawer-header"><h2>✧ AI Co-Pilot</h2>${btn('close','×','','aria-label="Close AI drawer"')}</div><div class="callout">Page context · ${esc(route)} · ${esc(state.selected)}<br>Local source-backed analysis</div><div class="actions">${link('ai','Open full conversation')}${btn('suggest','Show risk orders','','data-question="Which orders are most at risk?"')}</div><div class="spaced">${chatHTML()||'<h2>What can I help you understand?</h2><p class="muted">Ask about risks, a customer, or the selected order.</p>'}</div>${composer()}</aside></div>`;$('#overlay .drawer').scrollTop=100000}
function download(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target;const f=new FormData(form);if(form.id==='global-search'){go('orders?q='+encodeURIComponent(String(f.get('query')).trim()));return}if(form.dataset.form==='chat'){ask(String(f.get('visible-question')));return}if(form.id==='order-filters')return;if(form.id==='feasibility-form'){feasibility={category:f.get('category'),qty:Number(f.get('qty')),due:f.get('due'),outside:f.has('outside')};state.request={...feasibility};save();go('result');return}if(form.id==='draft-form'){const o=current();pending={order:o.id,recipient:String(f.get('recipient')).trim(),channel:f.get('channel'),text:String(f.get('message')).trim()};if(!pending.recipient||!pending.text){toast('Enter a recipient and message.');return}const p=pending;modal('Preview & confirm demo message',`<span class="badge">Simulation only</span><p class="spaced"><strong>${esc(p.recipient)}</strong> · ${p.channel}<br>${p.order}</p><pre>${esc(p.text)}</pre><p>No real message will be sent. Confirmation creates a simulated receipt and a local audit record.</p>`,'confirm-message','Confirm simulated send');pending=p;return}if(form.id==='settings-form'){const p={time:f.get('time'),idle:f.get('idle'),voice:f.has('voice'),briefing:f.has('briefing')};modal('Review preference changes',`<p>Briefing: ${p.briefing?'Enabled':'Disabled'} · ${p.time} SGT<br>Inactivity threshold: ${p.idle} days<br>Voice preference: ${p.voice?'On':'Off'}</p><p class="muted">Saved only in this browser. No scheduled service is activated.</p>`,'confirm-settings');pending=p}});
document.addEventListener('input',e=>{if(e.target.closest('#order-filters'))filterOrders()});
document.addEventListener('change',e=>{if(e.target.closest('#order-filters'))filterOrders();if(e.target.id==='audit-filter')$('#audit-results').innerHTML=auditRows(state.audit.filter(a=>!e.target.value||a.type===e.target.value))});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.closest('form')&&b.type==='submit'&&!b.dataset.action)return;e.preventDefault();const id=b.dataset.id;switch(b.dataset.action){
case 'menu':$('.sidebar').classList.toggle('open');break;
case 'close':closeOverlay();break;
case 'ai-drawer':openAIDrawer();break;
case 'ask-order':state.selected=id;openAIDrawer();ask('Why is '+id+' at risk?');break;
case 'suggest':ask(b.dataset.question);break;
case 'new-chat':state.chat=[];state.chatIds=[];save();render();break;
case 'go-feasibility':go('feasibility');break;
case 'clear-filters':$('#order-filters').reset();$$('#order-filters input').forEach(x=>x.value='');$$('#order-filters select').forEach(x=>x.value='');filterOrders();break;
case 'risk-select':riskId=id;render();break;
case 'exception-select':exception=id;render();break;
case 'exception-filter':$$('#exception-list button').forEach(x=>x.hidden=b.dataset.level!=='All'&&x.dataset.level!==b.dataset.level);b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));break;
case 'reset-feasibility':feasibility={category:'TOPS',qty:800,due:'2026-04-25',outside:true};render();break;
case 'save-assessment':modal('Save this assessment?',`<p>${feasibility.qty} ${feasibility.category}<br>Requested ${date(feasibility.due)}<br>Estimated ${date(estimate())}</p><p>This saves a scenario, without assigning a workshop.</p>`,'confirm-assessment');break;
case 'confirm-assessment':state.assessments.unshift({...feasibility,estimate:estimate()});audit('Assessment saved','Saved a demo planning scenario',state.assessments[0]);closeOverlay();toast('Assessment saved to Messages & Watches.');break;
case 'note':modal('Add an order note',`<label>Note for ${id}<textarea id="note-text" maxlength="2000" placeholder="Record a verified update…"></textarea></label>`,'confirm-note','Save note');pending=id;break;
case 'confirm-note':{const text=$('#note-text').value.trim();if(!text){toast('Enter a note before saving.');break}state.notes.unshift({id:pending,text,time:new Date().toISOString()});audit('Note added','Added a note to '+pending,{order:pending,text});closeOverlay();render();toast('Note saved.');break}
case 'watch':if(find(id||state.selected)?.status==='Complete'){toast('This order is complete. Choose an active order to create a watch.');break}modal('Review standing watch',`<p>Order ${id||state.selected}</p><label>Alert after inactivity reaches<select id="watch-threshold">${[1,2,3,5,7].map(n=>`<option ${String(n)===state.settings.idle?'selected':''} value="${n}">${n} calendar days</option>`).join('')}</select></label><p class="callout">Manual checks only. No background alerts or external messages.</p>`,'confirm-watch','Confirm watch');pending=id||state.selected;break;
case 'confirm-watch':{const w={id:'W-'+Date.now(),order:pending,threshold:Number($('#watch-threshold').value),active:true};state.watches.unshift(w);audit('Watch created','Created a local standing watch',w);closeOverlay();if(route==='messages')render();toast('Watch created. Review it in Messages & Watches.');break}
case 'toggle-watch':{const w=state.watches.find(x=>x.id===id);w.active=!w.active;audit('Watch updated',`${w.order} watch ${w.active?'resumed':'paused'}`,{...w});render();break}
case 'check-watch':{const w=state.watches.find(x=>x.id===id),o=find(w.order);w.last=o.idle>=w.threshold?`Triggered: ${o.idle} idle days ≥ ${w.threshold}. Based on fixed Apr 01 dataset snapshot.`:`No trigger: ${o.idle} idle days < ${w.threshold}. Based on fixed Apr 01 dataset snapshot.`;audit('Watch checked',w.last,{order:o.id,threshold:w.threshold});render();break}
case 'message-tab':messageTab=b.dataset.tab;render();break;
case 'regenerate':$('#draft-form textarea').value=makeDraft(current(),true);toast('Demo draft regenerated from the same order facts.');break;
case 'copy-draft':try{await navigator.clipboard.writeText($('#draft-form textarea').value);toast('Draft copied.')}catch{$('#draft-form textarea').select();toast('Select and copy the highlighted draft with Ctrl+C.')}break;
case 'confirm-message':{if(!pending)break;const m={...pending,id:'DEMO-MSG-'+String(state.messages.length+1).padStart(3,'0'),time:new Date().toISOString(),status:'Simulated receipt'};state.messages.unshift(m);audit('Demo message confirmed','Human confirmed a simulated chase-up for '+m.order,{...m,evidence:find(m.order),snapshot:SNAPSHOT,confirmation:'Explicit click: Confirm simulated send',realDelivery:false});closeOverlay();messageTab='messages';go('messages');toast('Simulated receipt created. No real message was sent.');break}
case 'confirm-settings':state.settings=pending;audit('Settings updated','Confirmed local preferences',{...pending});closeOverlay();render();toast('Preferences saved.');break;
case 'cancel-settings':render();toast('Unsaved preferences discarded.');break;
case 'reset-data':modal('Reset local demo data?', '<p>This clears this browser’s demo notes, watches, messages, audit history, assessments and chat. Original source files are unaffected.</p>','confirm-reset','Reset demo');break;
case 'confirm-reset':localStorage.removeItem('threadpilot-track1-v2');state=JSON.parse(JSON.stringify(defaults));feasibility={category:'TOPS',qty:800,due:'2026-04-25',outside:true};messageTab='watches';closeOverlay();render();toast('Local demo reset.');break;
case 'export-order':download(id+'-demo-source.json',find(id));break;
case 'export-audit':download('threadpilot-local-audit.json',state.audit);break;
case 'voice':modal('Voice input · demo',`<p>Live speech recognition is not connected. Edit the example transcript below to try the voice-to-question flow.</p><label>Transcript<textarea id="voice-transcript">Which orders are most at risk?</textarea></label>`,'confirm-voice','Use transcript');break;
case 'confirm-voice':{const q=$('#voice-transcript').value.trim();if(!q){toast('Enter a transcript.');break}closeOverlay();ask(q);break}
}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOverlay();if(e.key==='Tab'&&$('#overlay .overlay')){const list=$$('#overlay button, #overlay a, #overlay input, #overlay select, #overlay textarea').filter(x=>!x.disabled&&x.offsetParent!==null);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
window.addEventListener('hashchange',render);
